// <auto-generated />
namespace Repositorios.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class agregadoidentityenclaseparametros : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(agregadoidentityenclaseparametros));
        
        string IMigrationMetadata.Id
        {
            get { return "202111212324535_agregado identity en clase parametros"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
