// <auto-generated />
namespace Repositorios.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Tabla_param_cambio_nombre : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tabla_param_cambio_nombre));
        
        string IMigrationMetadata.Id
        {
            get { return "202111152256463_Tabla_param_cambio_nombre"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
